#!/usr/bin/env bash

set -euo pipefail

OLD_PASSWORD='raspberry'
NEW_PASSWORD="$OLD_PASSWORD"
PATH_TO_SSH_KEY="$HOME/.ssh/id_ed25519"
GIT_USER_EMAIL=''
GIT_USER_NAME=''
HOSTNAME="raspberrypi.local"
ENABLE_SPI=false
SHOULD_DELETE_SELF=false

usage(){
    echo "Usage: $(basename "${0}") [-n <NEW_PASSWORD>] [-h <HOSTNAME>] [-o <OLD_PASSWORD>] [-i <PATH_TO_SSH_KEY>] [-s] [-r]"
    echo "Run this from the raspberry pi."
    echo "  -p NEW_PASSWORD    : Set the new password. Defaults to $OLD_PASSWORD"
    echo "  -h HOSTNAME        : Set the hostname. Defaults to $HOSTNAME."
    echo "  -o OLD_PASSWORD    : defaults to: $OLD_PASSWORD"
    echo "  -i PATH_TO_SSH_KEY : defaults to: $PATH_TO_SSH_KEY"
    echo "  -e GIT_USER_EMAIL  : email address for git"
    echo "  -u GIT_USER_NAME   : user name for git"
    echo "  -s                 : Enable SPI"
    echo "  -r                 : delete self (this script) after running"
    exit 1
}

main(){
    trap 'fail $? $LINENO' ERR

    parseOpts "$@"

    setupSshKey
    updateAndInstallPackages
    setupGit
    installRmate
    clonePiTools
    changeAndSetupShell
    setTimezone
    setHostname
    maybeEnableSpi
    changePassword
    maybeDeleteSelf

    info "\\nRestarting..."
    info "Pi will be available via:\\n"
    info "  ssh pi@$HOSTNAME.local\\n"

    # redirect "sudo: unable to resolve host raspberrypi: Name or service not known" to /dev/null
    # I think sudo has weirdness immediately after a hostname change. Hide this output to avoid
    # someone thinking something didn't work (it's fine).
    sudo shutdown -r now 2>/dev/null
}

parseOpts(){
    while getopts ":p:h:o:i:e:u:sr" opt; do
        case ${opt} in
            p) NEW_PASSWORD=${OPTARG} ;;
            h)
                if [[ "$OPTARG" =~ ^[a-z]([a-z0-9-]*[a-z0-9])?$ ]]; then
                    HOSTNAME=${OPTARG}
                else
                    echo "Invalid hostname."
                    usage
                fi
                ;;
            o) OLD_PASSWORD=${OPTARG} ;;
            i) PATH_TO_SSH_KEY=${OPTARG} ;;
            e) GIT_USER_EMAIL=${OPTARG} ;;
            u) GIT_USER_NAME=${OPTARG} ;;
            s) ENABLE_SPI=true ;;
            r) SHOULD_DELETE_SELF=true ;;
            *) usage ;;
          esac
    done
}

setupSshKey(){
    info "\\nSetting up ssh key... If you still need to add this key to your github account, see: "
    info "https://docs.github.com/en/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account"
    info "https://github.com/settings/keys"
    eval "$(ssh-agent -s)"
    ssh-add "$PATH_TO_SSH_KEY"
    sleep 1 # ssh setup is randomly slow to complete. Wait a bit to avoid cloberring subsequent output lines.
}

updateAndInstallPackages(){
    info "\\nUpdating and installing packages..."
    sudo apt update
    sudo apt -y install git mlocate vim zsh zsh-syntax-highlighting
    sudo apt -y full-upgrade
}

# use diff-highlight as diff tool / pager
setupGit(){
    info "\\nSetting up git..."
    sudo make -C /usr/share/doc/git/contrib/diff-highlight
    git config --global core.pager '/usr/share/doc/git/contrib/diff-highlight/diff-highlight | less'
    if [[ -n ${GIT_USER_EMAIL} ]]; then
        info "\\nSetting git user email to $GIT_USER_EMAIL..."
        git config --global user.email "$GIT_USER_EMAIL"
    fi
    if [[ -n ${GIT_USER_NAME} ]]; then
        info "\\nSetting git user name to $GIT_USER_NAME..."
        git config --global user.name "$GIT_USER_NAME"
    fi

    git config --global pull.rebase true
}

# allows `subl path_to_file.txt` to use sublime text to edit the file on the pi
#
# This requires setting up ssh port forwarding for our port in the computer we are sshing from.
installRmate(){
    info "\\nInstalling rmate..."
    sudo wget -O /usr/local/bin/subl https://raw.githubusercontent.com/aurora/rmate/master/rmate
    sudo chmod a+x /usr/local/bin/subl
}

# Useful for the wifi_config script, shairport-sync installation, etc
clonePiTools(){
    info "\\nInstalling pitools..."
    dev_dir="$HOME/development"
    mkdir -p "$dev_dir"
    git -C "$dev_dir" clone https://github.com/dasl-/pitools.git
}

changeAndSetupShell(){
    info "\\nSetting up zsh shell..."

    # change default shell
    echo "$OLD_PASSWORD" | chsh -s /usr/bin/zsh

    # oh-my-zsh
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

    # iterm shell integration
    curl -L https://iterm2.com/shell_integration/zsh -o ~/.iterm2_shell_integration.zsh

    # fzf
    # We don't use apt to install fzf because the apt version is sometimes too old to be compatible with fzf-tab.
    # See: https://github.com/Aloxaf/fzf-tab/issues/189
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    ~/.fzf/install --key-bindings --completion --no-update-rc

    # fzf-tab: change native zsh autocomplete to always use fzf
    # https://github.com/Aloxaf/fzf-tab#install
    fzf_tab_dir="$HOME/.config/zsh"
    mkdir -p "$fzf_tab_dir"
    git -C "$fzf_tab_dir" clone https://github.com/Aloxaf/fzf-tab

    curl https://raw.githubusercontent.com/dasl-/pitools/main/homedir/.zshrc > "$HOME/.zshrc"

    curl https://raw.githubusercontent.com/dasl-/pitools/main/homedir/zsh_fix_history > "$HOME/zsh_fix_history"
    sudo chmod a+x "$HOME/zsh_fix_history"
}

setTimezone(){
    sudo timedatectl set-timezone UTC
}

# Allows sshing and hitting the pifi webpage via "<hostname>.local"
# See: https://www.raspberrypi.org/documentation/remote-access/ip-address.md "Resolving raspberrypi.local with mDNS"
setHostname(){
    info "\\nSetting hostname to: $HOSTNAME"
    echo "$HOSTNAME" | sudo tee /etc/hostname >/dev/null 2>&1
    sudo sed -i -E 's/(127\.0\.1\.1\s+)[^ ]+/\1'"$HOSTNAME"'/g' /etc/hosts
}

maybeEnableSpi(){
    if [[ ${ENABLE_SPI} == "true" ]]; then
        info "\\nEnabling SPI..."
        # https://raspberrypi.stackexchange.com/a/96679
        sudo raspi-config nonint do_spi 0
    fi
}

changePassword(){
    info "\\nChanging password to: $NEW_PASSWORD"
    echo -e "$OLD_PASSWORD\n$NEW_PASSWORD\n$NEW_PASSWORD" | passwd
    sleep 1 # password setup is randomly slow to complete. Wait a bit to avoid cloberring subsequent output lines.
}

maybeDeleteSelf() {
    if [[ ${SHOULD_DELETE_SELF} == "true" ]]; then
        SCRIPT_DIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
        SCRIPT_NAME=$(basename -- "${BASH_SOURCE[0]}")
        SCRIPT_PATH="$SCRIPT_DIR/$SCRIPT_NAME"
        info "\\nDeleting self ( $SCRIPT_PATH )..."
        rm "$SCRIPT_PATH"
    fi
}

fail(){
    local exit_code=$1
    local line_no=$2
    die "Error at line number: $line_no with exit code: $exit_code"
}

info() {
    echo -e "\x1b[32m$*\x1b[0m" # green stdout
}

die() {
    echo
    echo -e "\x1b[31m$*\x1b[0m" >&2 # red stderr
    exit 1
}

main "$@"
