#!/usr/bin/env bash

set -euo pipefail -o errtrace

main(){
    trap 'fail $? $LINENO' ERR

    installGrafana
    configureGrafana
    setupSystemd

    local grafana_url
    grafana_url="http://$(hostname).local:3000"
    info "\\nFinished installing grafana. Wait ~1 minute for it to be ready; then access it at: $grafana_url"
}

installGrafana(){
    # https://grafana.com/tutorials/install-grafana-on-raspberry-pi/#install-grafana
    info "\\nInstalling grafana..."

    info "\\nConfiguring apt source..."
    wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -
    local grafana_apt_source='deb https://packages.grafana.com/oss/deb stable main'
    if ! sudo grep -q "^$grafana_apt_source" /etc/apt/sources.list.d/grafana.list ; then
        echo "$grafana_apt_source" | sudo tee -a /etc/apt/sources.list.d/grafana.list
    fi

    info "\\nInstalling package..."
    sudo apt-get update
    sudo apt-get install -y grafana
}

configureGrafana(){
    info "\\nConfiguring grafana..."

    # Move storage of grafana sqlite DB to external SSD to ensure speedy, stable access
    info "\\nSetting up data storage on external SSD..."
    sudo mkdir -p /ssd/grafana-data
    sudo chown -R grafana:grafana /ssd/grafana-data
    # See: https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#data
    sudo sed -i -e 's|^;data = /var/lib/grafana|data = /ssd/grafana-data|' /etc/grafana/grafana.ini

    info "\\nConfiguring auth..."
    # Don't require logging in to view the dashboards
    # See: https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/#anonymous-authentication
    sudo sed -i -z -e 's|# enable anonymous access\n;enabled = false|# enable anonymous access\nenabled = true|' /etc/grafana/grafana.ini

    # Don't require users to login so frequently
    # https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/#login-and-short-lived-tokens
    sudo sed -i -e 's|^;login_maximum_inactive_lifetime_duration =|login_maximum_inactive_lifetime_duration = 10y|' /etc/grafana/grafana.ini
    sudo sed -i -e 's|^;login_maximum_lifetime_duration =|login_maximum_lifetime_duration = 10y|' /etc/grafana/grafana.ini
}

setupSystemd(){
    info "\\nSetting up systemd..."
    sudo systemctl enable grafana-server
    sudo systemctl daemon-reload
    sudo systemctl restart grafana-server
}

fail(){
    local exit_code=$1
    local line_no=$2
    local script_name
    script_name=$(basename "${BASH_SOURCE[0]}")
    die "Error in $script_name at line number: $line_no with exit code: $exit_code"
}

info(){
    echo -e "\x1b[32m$*\x1b[0m" # green stdout
}

warn(){
    echo -e "\x1b[33m$*\x1b[0m" # yellow stdout
}

die(){
    echo
    echo -e "\x1b[31m$*\x1b[0m" >&2 # red stderr
    exit 1
}

main "$@"
