# Observability
:toc:
:toclevels: 5

## Summary
. Install node_exporter on all pis
. Install pitoolsmon on all pis
. install timestamped_exporter, grafana, and prometheus on one host: study.local
. Access grafana at http://study.local:3000

## node_exporter dsh install command
....
dsh --remoteshell ssh --remoteshellopt '-o UserKnownHostsFile=/dev/null' --remoteshellopt '-o StrictHostKeyChecking=no' --remoteshellopt '-o LogLevel=ERROR' --concurrent-shell --show-machine-names --machine pi@study.local,pi@pifi.local,pi@kitchen.local,pi@watchcat.local,pi@bedroom.local,pi@piwall.local,pi@piwall1.local,pi@piwall2.local,pi@piwall3.local,pi@piwall4.local,pi@piwall5.local,pi@piwall6.local,pi@piwall7.local,pi@piwall8.local,pi@piwall9.local,pi@piwall10.local 'cd /home/pi/development/pitools && git pull && /home/pi/development/pitools/observability/install_node_exporter' && sleep 5 && echo 'study,pifi,kitchen,watchcat,bedroom,piwall,piwall1,piwall2,piwall3,piwall4,piwall5,piwall6,piwall7,piwall8,piwall9,piwall10' | sed 's/,/\n/g' | parallel --tag --keep-order --max-args 1 --jobs 0 --will-cite curl --silent {}.local:9100/metrics | grep 'promhttp_metric_handler_requests_total{code="200"}'
....

## pitoolsmon dsh install command
Pitoolsmon is a custom pitools monitoring script that emits various pi metrics to prometheus. Install `node_exporter` before installing pitoolsmon.
....
dsh --remoteshell ssh --remoteshellopt '-o UserKnownHostsFile=/dev/null' --remoteshellopt '-o StrictHostKeyChecking=no' --remoteshellopt '-o LogLevel=ERROR' --concurrent-shell --show-machine-names --machine pi@study.local,pi@pifi.local,pi@kitchen.local,pi@watchcat.local,pi@bedroom.local,pi@piwall.local,pi@piwall1.local,pi@piwall2.local,pi@piwall3.local,pi@piwall4.local,pi@piwall5.local,pi@piwall6.local,pi@piwall7.local,pi@piwall8.local,pi@piwall9.local,pi@piwall10.local 'cd /home/pi/development/pitools && git pull && /home/pi/development/pitools/observability/install_pitoolsmon' && sleep 11 && echo 'study,pifi,kitchen,watchcat,bedroom,piwall,piwall1,piwall2,piwall3,piwall4,piwall5,piwall6,piwall7,piwall8,piwall9,piwall10' | sed 's/,/\n/g' | parallel --tag --keep-order --max-args 1 --jobs 0 --will-cite 'curl --silent {}.local:9100/metrics | grep -E "^pitoolsmon_throttling_has_occurred"'
....

## timestamped_exporter
The timestamped_exporter is a custom implementation of the node_exporter's https://github.com/prometheus/node_exporter?tab=readme-ov-file#textfile-collector[textfile collector]. We need this custom implementation because we have a use case for associating custom timestamps with certain metrics. The node_exporter's textfile collector does not support this:

> Note: Timestamps are not supported.

In order to use custom timestamps that are more than an hour delta from the current time, we needed to enable prometheus's https://promlabs.com/blog/2022/10/05/whats-new-in-prometheus-2-39/#experimental-out-of-order-ingestion[`out_of_order_time_window`] feature. Otherwise we'd get errors like this:

....
Jul  6 13:12:40 study PROMETHEUS[1733468]: ts=2024-07-06T13:12:40.583Z caller=scrape.go:1729 level=warn component="scrape manager" scrape_pool=node target=http://study:9101/metrics msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=1
....

The timestamped_exporter is simply a python server that concatenates and serves any `*.prom` files in the directory: `/home/pi/observability/timestamped_textfile_collector_data`. Those metrics will be served at `http://<hostname>:9101/metrics`.

See https://github.com/dasl-/pitools/blob/main/sensors/measure_city_data[`measure_city_data`] for an example of how to write timestamped `*.prom` files such that the timestamped_exporter can export them to prometheus.

See my [blog post](https://dasl.cc/2024/07/07/setting-custom-timestamps-for-prometheus-metrics/) on timestamped Prometheus metrics for more details.

## Grafana configuration
. The username and password is admin / admin by default on first login. Change password to same as WiFi password. : http://study.local:3000
. Add prometheus datasource http://study.local:3000/connections/datasources :
.. HTTP > Prometheus server URL: `http://localhost:9090`
.. Interval behaviour > Scrape interval: `10s`
.. Performance > Prometheus type: `Prometheus`
. Add https://grafana.com/grafana/dashboards/1860-node-exporter-full/["Node Exporter Full"] dashboard http://study.local:3000/dashboard/import :
.. Import via grafana.com: `1860` (this is the dashboard ID)
. Setup email alerting smtp server
.. Edit `/etc/grafana/grafana.ini`
.. Add the https://gist.github.com/dasl-/4cfd313b284ccb25f7e87814a87a9584[smtp config]
.. Note that it requires using a gmail "app password". It's saved in bitwarden.
.. Restart Grafana: `sudo systemctl restart grafana-server.service`

## Files used
The grafana DB is a sqlite file. We moved it from its default location (`/var/lib/grafana/grafana.db`) to a new location (`/ssd/grafana-data/grafana.db`). This is because the new location is on external SSD storage, which is faster and more reliable.

Prometheus stores data at the path specified by the `--storage.tsdb.path` flag.

## Backup grafana data
It's a good idea to back up your dashboards data periodically. Currently the process is manual. Dashboards data includes the json that defines the dashboard. It does NOT include the prometheus time series DB.
....
ssh pi@study.local 'sudo chmod a+r /ssd/grafana-data/grafana.db' && scp pi@study.local:/ssd/grafana-data/grafana.db ~/Downloads
....
Upload it here: https://drive.google.com/drive/u/0/folders/1ykL8-Zm2OvSODugE2xQGHNE5xXOhoz8o

## Issues we've seen before

### Browser unable to render grafana page with "failed to load its application files" error message

Navigating to the grafana URL would show an https://github.com/grafana/grafana/issues/65759[error page], but only on some clients. It turned out this was because my iOS version of safari was outdated and no longer https://grafana.com/docs/grafana/latest/setup-grafana/installation/#supported-web-browsers[supported] by grafana. Perhaps this happened after I upgraded to a new grafana version which no longer supported my browser. I solved this by upgrading iOS (which upgrades safari).
