# Observability
:toc:
:toclevels: 5

## Summary
. Install node_exporter on all pis
. install grafana and prometheus on one host: study.local
. Access grafana at http://study.local:3000

## node_exporter dsh install command
....
dsh --remoteshell ssh --remoteshellopt '-o UserKnownHostsFile=/dev/null' --remoteshellopt '-o StrictHostKeyChecking=no' --remoteshellopt '-o LogLevel=ERROR' --concurrent-shell --show-machine-names --machine pi@study.local,pi@pifi.local,pi@kitchen.local,pi@bedroom.local,pi@piwall.local,pi@piwall1.local,pi@piwall2.local,pi@piwall3.local,pi@piwall4.local,pi@piwall5.local,pi@piwall6.local,pi@piwall7.local,pi@piwall8.local,pi@piwall9.local,pi@piwall10.local 'cd /home/pi/development/pitools && git pull && /home/pi/development/pitools/observability/install_node_exporter' && sleep 5 && echo 'study,pifi,kitchen,bedroom,piwall,piwall1,piwall2,piwall3,piwall4,piwall5,piwall6,piwall7,piwall8,piwall9,piwall10' | sed 's/,/\n/g' | parallel --tag --keep-order --max-args 1 --jobs 0 --will-cite curl --silent {}.local:9100/metrics | grep 'promhttp_metric_handler_requests_total{code="200"}'
....

## pitoolsmon dsh install command
Pitoolsmon is a custom pitools monitoring script that emits various pi metrics to prometheus. Install `node_exporter` before installing pitoolsmon.
....
dsh --remoteshell ssh --remoteshellopt '-o UserKnownHostsFile=/dev/null' --remoteshellopt '-o StrictHostKeyChecking=no' --remoteshellopt '-o LogLevel=ERROR' --concurrent-shell --show-machine-names --machine pi@study.local,pi@pifi.local,pi@kitchen.local,pi@bedroom.local,pi@piwall.local,pi@piwall1.local,pi@piwall2.local,pi@piwall3.local,pi@piwall4.local,pi@piwall5.local,pi@piwall6.local,pi@piwall7.local,pi@piwall8.local,pi@piwall9.local,pi@piwall10.local 'cd /home/pi/development/pitools && git pull && /home/pi/development/pitools/observability/install_pitoolsmon' && sleep 11 && echo 'study,pifi,kitchen,bedroom,piwall,piwall1,piwall2,piwall3,piwall4,piwall5,piwall6,piwall7,piwall8,piwall9,piwall10' | sed 's/,/\n/g' | parallel --tag --keep-order --max-args 1 --jobs 0 --will-cite 'curl --silent {}.local:9100/metrics | grep -E "^pitoolsmon_throttling_has_occurred"'
....

## Grafana configuration
. The username and password is admin / admin by default on first login. Change password to same as WiFi password. : http://study.local:3000
. Add prometheus datasource http://study.local:3000/connections/datasources :
.. HTTP > Prometheus server URL: `http://localhost:9090`
.. Interval behaviour > Scrape interval: `10s`
.. Performance > Prometheus type: `Prometheus`
. Add https://grafana.com/grafana/dashboards/1860-node-exporter-full/["Node Exporter Full"] dashboard http://study.local:3000/dashboard/import :
.. Import via grafana.com: `1860` (this is the dashboard ID)

## Files used
The grafana DB is a sqlite file: `sudo sqlite3 /var/lib/grafana/grafana.db`

Prometheus stores data at the path specified by the `--storage.tsdb.path` flag.

## Backup grafana data
It's a good idea to back up your dashboards data periodically. Currently the process is manual. Dashboards data includes the json that defines the dashboard. It does NOT include the prometheus time series DB.
....
ssh pi@study.local 'sudo chmod a+r /var/lib/grafana/grafana.db' && scp pi@study.local:/var/lib/grafana/grafana.db ~/Downloads
....
Upload it here: https://drive.google.com/drive/u/0/folders/1ykL8-Zm2OvSODugE2xQGHNE5xXOhoz8o
