#!/usr/bin/env bash

set -euo pipefail -o errtrace

BASE_DIR="$(dirname "$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )")"

main(){
    trap 'fail $? $LINENO' ERR

    info "\\nInstalling city data measurer..."

    updatePackages
    setupSystemd

    info "\\nFinished installing PMSA003I."

    if [ -f $RESTART_REQUIRED_FILE ]; then
        info "Restarting..."
        sudo shutdown -r now
    fi
}

updatePackages(){
    info "Updating and installing packages..."
    sudo PIP_BREAK_SYSTEM_PACKAGES=1 python3 -m pip install --upgrade requests
}

setupSystemd(){
    info "\\nSetting up systemd..."

cat <<-EOF | sudo tee /etc/systemd/system/measure_city_data.service >/dev/null
[Unit]
Description=Measures city data, e.g. air quality
After=network-online.target
Wants=network-online.target

[Service]
Environment=HOME=/root
ExecStart=$BASE_DIR/sensors/measure_city_data
Restart=on-failure
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=MEASURE_CITY_DATA

[Install]
WantedBy=multi-user.target
EOF

    sudo chown root:root /etc/systemd/system/measure_city_data.service
    sudo chmod 644 /etc/systemd/system/measure_city_data.service
    sudo systemctl enable /etc/systemd/system/measure_city_data.service
    sudo systemctl daemon-reload
    sudo systemctl restart measure_city_data.service
}

fail(){
    local exit_code=$1
    local line_no=$2
    local script_name
    script_name=$(basename "${BASH_SOURCE[0]}")
    die "Error in $script_name at line number: $line_no with exit code: $exit_code"
}

info(){
    echo -e "\x1b[32m$*\x1b[0m" # green stdout
}

warn(){
    echo -e "\x1b[33m$*\x1b[0m" # yellow stdout
}

die(){
    echo
    echo -e "\x1b[31m$*\x1b[0m" >&2 # red stderr
    exit 1
}

main "$@"
