# External Harddrives

:toc:
:toclevels: 5

## Installing them
See Jeff Geerling's https://www.pidramble.com/wiki/benchmarks/external-usb-drives#format-a-usb-connected-drive-on-the-raspberry-pi-in-raspbian[guide]

### Format the drive
. `sudo fdisk -l`
. `sudo fdisk /dev/sda`
. `sudo mkfs -t ext4 /dev/sda1*`

### Mount the drive
. `sudo mkdir /ssd`
. `sudo mount /dev/sda1* /ssd`
. edit `/etc/fstab`
. reboot to confirm it gets automatically mounted

Add to `/etc/fstab`:
....
# USB SSD drive
/dev/sda1             /ssd            ext4    defaults,noatime  0       1
....

## Benchmarking USB drive performance
TLDR: USB SSD drive is much faster than SD card.

Running the benchmarks from Jeff Geerling's https://www.pidramble.com/wiki/benchmarks/microsd-cards#benchmarks[guide] on a raspberry pi 3b+ with 128GB external USB SSD drive and the samsung SD card.

SD card:
....
% sudo hdparm -t /dev/mmcblk0

/dev/mmcblk0:
 Timing buffered disk reads:  64 MB in  3.01 seconds =  21.27 MB/sec

% sudo dd if=/dev/zero of=/home/pi/test bs=8k count=50k conv=fsync; sudo rm -f /home/pi/test
51200+0 records in
51200+0 records out
419430400 bytes (419 MB, 400 MiB) copied, 41.0435 s, 10.2 MB/s

% ./iozone -e -I -a -s 100M -r 4k -i 0 -i 1 -i 2 -f /home/pi/test
    Iozone: Performance Test of File I/O
            Version $Revision: 3.506 $
        Compiled for 64 bit mode.
        Build: linux-arm

    Contributors:William Norcott, Don Capps, Isom Crawford, Kirby Collins
                 Al Slater, Scott Rhine, Mike Wisner, Ken Goss
                 Steve Landherr, Brad Smith, Mark Kelly, Dr. Alain CYR,
                 Randy Dunlap, Mark Montague, Dan Million, Gavin Brebner,
                 Jean-Marc Zucconi, Jeff Blomberg, Benny Halevy, Dave Boone,
                 Erik Habbinga, Kris Strecker, Walter Wong, Joshua Root,
                 Fabrice Bacchella, Zhenghua Xue, Qin Li, Darren Sawyer,
                 Vangel Bojaxhi, Ben England, Vikentsi Lapa,
                 Alexey Skidanov, Sudhir Kumar.

    Run began: Mon Oct  9 19:26:58 2023

    Include fsync in write timing
    O_DIRECT feature enabled
    Auto Mode
    File size set to 102400 kB
    Record Size 4 kB
    Command line used: ./iozone -e -I -a -s 100M -r 4k -i 0 -i 1 -i 2 -f /home/pi/test
    Output is in kBytes/sec
    Time Resolution = 0.000001 seconds.
    Processor cache size set to 1024 kBytes.
    Processor cache line size set to 32 bytes.
    File stride size set to 17 * record size.
                                                                    random    random      bkwd     record     stride
              kB  reclen    write    rewrite      read    reread      read     write      read    rewrite       read    fwrite  frewrite     fread   freread
          102400       4      2459      2101      6022      6446      6685      1474

iozone test complete.
....

USB SSD:
....
 % sudo hdparm -t /dev/sda

/dev/sda:
 Timing buffered disk reads:  92 MB in  3.01 seconds =  30.58 MB/sec

% sudo dd if=/dev/zero of=/ssd/test bs=8k count=50k conv=fsync; sudo rm -f /ssd/test
51200+0 records in
51200+0 records out
419430400 bytes (419 MB, 400 MiB) copied, 12.6891 s, 33.1 MB/s

% sudo ./iozone -e -I -a -s 100M -r 4k -i 0 -i 1 -i 2 -f /ssd/test
    Iozone: Performance Test of File I/O
            Version $Revision: 3.506 $
        Compiled for 64 bit mode.
        Build: linux-arm

    Contributors:William Norcott, Don Capps, Isom Crawford, Kirby Collins
                 Al Slater, Scott Rhine, Mike Wisner, Ken Goss
                 Steve Landherr, Brad Smith, Mark Kelly, Dr. Alain CYR,
                 Randy Dunlap, Mark Montague, Dan Million, Gavin Brebner,
                 Jean-Marc Zucconi, Jeff Blomberg, Benny Halevy, Dave Boone,
                 Erik Habbinga, Kris Strecker, Walter Wong, Joshua Root,
                 Fabrice Bacchella, Zhenghua Xue, Qin Li, Darren Sawyer,
                 Vangel Bojaxhi, Ben England, Vikentsi Lapa,
                 Alexey Skidanov, Sudhir Kumar.

    Run began: Mon Oct  9 19:40:14 2023

    Include fsync in write timing
    O_DIRECT feature enabled
    Auto Mode
    File size set to 102400 kB
    Record Size 4 kB
    Command line used: ./iozone -e -I -a -s 100M -r 4k -i 0 -i 1 -i 2 -f /ssd/test
    Output is in kBytes/sec
    Time Resolution = 0.000001 seconds.
    Processor cache size set to 1024 kBytes.
    Processor cache line size set to 32 bytes.
    File stride size set to 17 * record size.
                                                                    random    random      bkwd     record     stride
              kB  reclen    write    rewrite      read    reread      read     write      read    rewrite       read    fwrite  frewrite     fread   freread
          102400       4     10835     12687     12420     12554      8040     12724

iozone test complete.
....

## Equipment
https://www.amazon.com/dp/B06XWRRMYX?psc=1&ref=ppx_yo2ov_dt_b_product_details[UGREEN hard drive enclosure] is compatible with raspberry pi. It gets better speeds than other enclosures on benchmarks.

https://www.amazon.com/Samsung-Class-Micro-Adapter-MB-MC32DA/dp/B00WR4IJBE/ref=as_li_ss_tl?keywords=samsung+evo++microsd&qid=1562707245&s=gateway&sr=8-5&linkCode=ll1&tag=mmjjg-20&linkId=019797e6b450340f7d7c739ae8ad1203&language=en_US[Samsung EVO Plus SD card], recommended by https://www.jeffgeerling.com/blog/2019/raspberry-pi-microsd-card-performance-comparison-2019[Jeff Geerling's guide].
